name: zonedojo
description: A modern responsive Flutter web experience for ZoneDojo.
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
